version: 1.0.{build}
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: c7+40CsA5bKhsZI8kOgRQabWLPnrJuOqzGWPZ3v78LxwUY9Hi60KUV6CoiDYQk+1